### ISSUE TITLE
Project to-do list

### ISSUE THREAD

**Issue by wcjochem** [wpgp/imcover#1]
- [ ] Add region assignments for missing countries
- [ ] Add other region assignments
- [X] Interactive plots
- [ ] Expand data on year of introduction to more vaccines
- [ ] Check documentation (parameters, defaults, etc.)
- [ ] Add example code to key function docs
- [ ] Additional vignettes/tutorials
- [x] Check tidyverse compatibility
- [ ] Check code coverage of tests
- [x] Update stan model for user-defined priors
- [x] Add country-specific model
- [x] Add WUENIC data to plots
- [ ] Build pkgdown website
